# Esto es para Desarrollo solamente, para que refresque los archivos mientras desarrollamos

version: '3'

services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      # maps the current directory outside the container to the app directory inside the container
      - .:/app

  tests: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      # maps the current directory outside the container to the app directory inside the container
      - .:/app
    command: ["npm", "run", "test"]
