# use an existing docker image as base
FROM node:alpine

# copy files
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .

# tell the image what to do when it starts as a container
CMD ["npm", "run", "start"]
